# fly.toml app configuration file generated for shopsaas-redis on 2025-10-19T02:10:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shopsaas-redis'
primary_region = 'sin'

[build]
  image = "redis:7-alpine"
  dockerfile_inline = """
FROM redis:7-alpine
RUN echo 'requirepass $REDIS_PASSWORD' >> /usr/local/etc/redis/redis.conf
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
"""

# Redis password is set as a secret

[http_service]
  internal_port = 6379
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 6379

[checks]
  [checks.redis_ping]
    port = 6379
    type = 'tcp'
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  size = 'shared-cpu-1x'
